/*
 * This header provides constants for the pm8xxx gpio binding.
 */

#ifndef _DT_BINDINGS_PINCTRL_QCOM_PM8XXX_GPIO_H
#define _DT_BINDINGS_PINCTRL_QCOM_PM8XXX_GPIO_H

#define PM8XXX_GPIO_PULL_UP_30		1
#define PM8XXX_GPIO_PULL_UP_1P5		2
#define PM8XXX_GPIO_PULL_UP_31P5	3
#define PM8XXX_GPIO_PULL_UP_1P5_30	4

#define PM8XXX_GPIO_VIN_BB		0
#define PM8XXX_GPIO_VIN_L2		1
#define PM8XXX_GPIO_VIN_L3		2
#define PM8XXX_GPIO_VIN_L4		3
#define PM8XXX_GPIO_VIN_L5		4
#define PM8XXX_GPIO_VIN_L6		5
#define PM8XXX_GPIO_VIN_L7		6
#define PM8XXX_GPIO_VIN_L8		7
#define PM8XXX_GPIO_VIN_L11		8
#define PM8XXX_GPIO_VIN_L14		9
#define PM8XXX_GPIO_VIN_L15		10
#define PM8XXX_GPIO_VIN_L17		11
#define PM8XXX_GPIO_VIN_S3		12
#define PM8XXX_GPIO_VIN_S4		13
#define PM8XXX_GPIO_VIN_VPH		14

#define	PM8XXX_GPIO_STRENGTH_NO		0
#define	PM8XXX_GPIO_STRENGTH_HIGH	1
#define	PM8XXX_GPIO_STRENGTH_MED	2
#define	PM8XXX_GPIO_STRENGTH_LOW	3

#endif
